ANIMATION: True
VERBOSE: False # print detailed debug message

SIM_LOOP: 500
MAX_ROAD_WIDTH: 3.5 # maximum road width [m]
D_ROAD_W: 0.2 # road width sampling length [m]
MAX_T: 8.0 # max prediction time [m]
MIN_T: 7.0 # min prediction time [m]
DT: 0.1 # time tick [s]
D_T_S: 5.0 # target longtitude vel sampling length [km/h]
N_S_SAMPLE: 1 # sampling number of target longtitude vel
MAX_SPEED: 50.0 # maximum speed [km/h]
MAX_ACCEL: 3.0 # maximum acceleration [m/s^2]
MAX_CURVATURE: 1.0 # maximum curvature [1/m]

# 可以参数辨识
weights:
  W_YAW: 1.0 # smoothness cost yaw difference
  W_CUR: 1.0 # curvature cost
  W_VEL_DIFF: 1.0e-1 # velocity diff cost
  W_T: 1.0 # time cost
  W_OBS: 1.0 # obstacle cost
  W_GUIDE: 5.0 # guidance cost
  W_ACC: 1.0 # acceleration cost
  W_JERK: 1.0 # jerk cost
  W_COLLISION: 4.0 # collision cost
  W_STOP: 100 # punishment for stop

vehicle:
  truck:
    length: 5 # 车长
    width: 2 #车宽
    L: 2.9 # wheel base 轴距
    R: 1.5 # minimum turning radius 最小转弯半径
    ds: 0.1 # course distanse
  car:
    #todo:
